HarrysGroceryStore/Models/Product/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    public class Cart
    {
        private List<CartItem> items = new List<CartItem>();

        public virtual IEnumerable<CartItem> Items
        {
            get { return items; }
        }

        public decimal TotalValue
        {
            get { return items.Sum(i => i.SubTotal); }
        }

        public virtual void AddItem(Product product, int quantity)
        {
            CartItem item = items.Where(i => i.Product.ProductId == product.ProductId).FirstOrDefault();
            if (item == null)
            {
                item = new CartItem { Product = product, Quantity = quantity };
                items.Add(item);
            }
            else
            {
                item.Quantity += quantity;
            }
        }

        public virtual void Clear()
        {
            items.Clear();
        }

        public virtual void RemoveItem(Product product)
        {
            items.RemoveAll(i => i.Product.ProductId == product.ProductId);
        }
    }
}

HarrysGroceryStore/Models/Product/CartItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    public class CartItem
    {
        public int CartItemId { get; set; }

        public Product Product { get; set; }

        public int Quantity { get; set; }

        public decimal SubTotal
        {
            get { return Quantity * Product.Price; }
        }
    }
}

HarrysGroceryStore/Models/Product/EfProductRepository.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    public class EfProductRepository : IProductRepository
    {
        private AppDbContext _context;

        public EfProductRepository(AppDbContext context)
        {
            _context = context;
        }

        public Product AddProduct(Product product)
        {
            _context.Products.Add(product);
            _context.SaveChanges();
            return product;
        }

        public IQueryable<string> GetAllCategories()
        {
            IQueryable<string> categories = _context.Products.Select(p => p.Category).Distinct().OrderBy(c => c);
            return categories;
        }

        public IQueryable<Product> GetAllProducts()
        {
            return _context.Products;
        }

        public Product GetProductById(int productId)
        {
            Product p = _context.Products.Find(productId);
            return p;
        }

        public IQueryable<Product> GetProductsByKeyword(string keyword)
        {
            IQueryable<Product> products = _context.Products.Where(p => p.ProductName.Contains(keyword));
            return products;
        }

        public Product UpdateProduct(Product product)
        {
            Product productToUpdate = _context.Products.Find(product.ProductId);
            if (productToUpdate != null)
            {
                productToUpdate.ProductName = product.ProductName;
                productToUpdate.Price = product.Price;
                productToUpdate.Category = product.Category;
                _context.SaveChanges();
            }
            return productToUpdate;
        }

        public bool DeleteProduct(int id)
        {
            Product productToDelete = GetProductById(id);
            if (productToDelete == null)
            {
                return false;
            }
            _context.Products.Remove(productToDelete);
            _context.SaveChanges();
            return true;
        }
    }
}

HarrysGroceryStore/Models/Product/IProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    public interface IProductRepository
    {
        public Product AddProduct(Product product);

        public IQueryable<Product> GetAllProducts();

        public Product GetProductById(int productId);

        public IQueryable<Product> GetProductsByKeyword(string keyword);

        public IQueryable<string> GetAllCategories();

        public Product UpdateProduct(Product product);

        public bool DeleteProduct(int id);
    }
}

HarrysGroceryStore/Models/Product/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    [Table("Products")]
    
    public class Product
    {
        [Key]
        public int ProductId { get; set; }

        public string ProductName { get; set; }

        [Column(TypeName = "decimal(8, 2")]
        public decimal Price { get; set; }

        public string Category { get; set; }

        [ForeignKey("Supplier")]
        public int SupplierId { get; set; }
        public Supplier Supplier { get; set; }

        public List<OrderDetail> OrderDetail { get; set; }
    }
}

HarrysGroceryStore/Components/NavigationMenuViewComponent.cs
using HarrysGroceryStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository _repository;

        public NavigationMenuViewComponent(IProductRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            IQueryable<string> categories = _repository.GetAllCategories();
            return View(categories);
        }
    }
}

HarrysGroceryStore/Controllers/Product/ProductController.cs
using HarrysGroceryStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Controllers
{
    public class ProductController : Controller
    {
        private int _pageSize = 10;
        private IProductRepository _repository;

        public ProductController(IProductRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddProduct(Product product)
        {
            _repository.AddProduct(product);
            return RedirectToAction("Index");
        }

        public IActionResult ProductCategories()
        {
            IQueryable<string> categories = _repository.GetAllCategories();
            return View(categories);
        }

        public IActionResult Index(string category, int page = 1)
        {
            IQueryable<Product> allProducts = _repository.GetAllProducts();
            IQueryable<Product> someProducts; 
            
            if (category == null)
            {
                someProducts = allProducts.OrderBy(p => p.ProductId).Skip((page - 1) * _pageSize).Take(_pageSize);
            }
            else
            {
                someProducts = allProducts.OrderBy(p => p.ProductId).Where(p => p.Category == category).Skip((page - 1) * _pageSize).Take(_pageSize);
            }
            
            ListViewModel lvm = new ListViewModel();

            PagingInfo pi = new PagingInfo();
            pi.TotalItems = allProducts.Count();
            pi.ItemsPerPage = _pageSize;
            pi.CurrentPage = page;

            lvm.PagingInformation = pi;

            lvm.Products = someProducts;

            lvm.CurrentCategory = category;

            return View(lvm);
        }

        public IActionResult ProductDetail(int id)
        {
            Product product = _repository.GetProductById(id);
            if (product != null)
            {
                return View(product);
            }
            return RedirectToAction("Index");
        }

        public IActionResult SearchProduct(string keyword)
        {
            IQueryable<Product> product = _repository.GetProductsByKeyword(keyword);
            return View(product);
        }

        [HttpGet]
        public IActionResult UpdateProduct(int id)
        {
            Product product = _repository.GetProductById(id);
            if (product != null)
            {
                return View(product);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UpdateProduct(Product product)
        {
            Product updatedProduct = _repository.UpdateProduct(product);
            return RedirectToAction("ProductDetail", new { id = product.ProductId });
        }

        [HttpGet]
        public IActionResult DeleteProduct(int id)
        {
            Product product = _repository.GetProductById(id);
            if (product != null)
            {
                return View(product);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteProduct(Product product, int id)
        {
            _repository.DeleteProduct(id);
            return RedirectToAction("Index");
        }
    }
}

HarrysGroceryStore/Views/Product/AddProduct.cshtml
@model Product

<form asp-controller="Product" asp-action="AddProduct" method="post">
    <table>
        <tr>
            <th><label class="font-weight-bold" asp-for="ProductName"> Product Name: </label></th>
            <td> <input asp-for="ProductName" /> </td>
        </tr>
        <tr>
            <th><label class="font-weight-bold" asp-for="Category"> Category: </label></th>
            <td> <input asp-for="Category" /> </td>
        </tr>
        <tr>
            <th> <label class="font-weight-bold" asp-for="Price"> Price: </label> </th>
            <td> <input asp-for="Price" /> </td>
        </tr>
        <tr>
            <th></th>
            <td> <input type="submit" class="btn btn-dark" value="Add Product" /> <input type="submit" class="btn btn-dark" asp-action="Index" value="Back" /> </td>
        </tr>
    </table>
</form>

HarrysGroceryStore/Views/Product/DeleteProduct.cshtml
@model Product

<table>
    <tr>
        <th class="text-right"> Product Name: </th>
        <td class="p-2"> @Model.ProductName </td>
    </tr>
    <tr>
        <th class="text-right"> Category: </th>
        <td class="p-2"> @Model.Category </td>
    </tr>
    <tr>
        <th class="text-right"> Unit Price: </th>
        <td class="p-2"> @Model.Price.ToString("C") </td>
    </tr>
</table>
<hr />

<h4> Are You Sure? </h4>
<form method="post">
    <input type="submit" asp-action="DeleteProduct" class="btn btn-dark" value="Delete" />
    <input type="submit" asp-action="ProductDetail" class="btn btn-dark" asp-route-id="@Model.ProductId" formmethod="get" value="Cancel" />
</form>

HarrysGroceryStore/Views/Product/Index.cshtml
@model ListViewModel


<div class="bg-dark p-2 text-white text-center">
    <h3><span class="navbar-brand ml-2 badge"> Welcome To Harrys Grocery Store </span></h3>
</div>

<div class="row m-1 p-1">
    <div id="categories" class="col-3">
        <vc:navigation-menu />
    </div>
    <div class="col-9">
        @foreach (var product in Model.Products)
        {
            <div class="card card-outline-primary m-1 p-1">
                <div class="fg-faded p-1">
                    <h4>
                        <a asp-action="ProductDetail" asp-route-id="@product.ProductId"> @product.ProductName </a>
                        <span class="badge badge-pill badge-primary" style="float: right;">
                            <small> @product.Price.ToString("C") </small>
                        </span>
                    </h4>
                </div>
                <div>
                    Category: @product.Category
                </div>

                <form asp-page="/Cart" method="post">
                    <input type="hidden" asp-for="@product.ProductId" name="ProductId" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <span class="card-text p-1">
                        <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                            Add To Cart
                        </button>
                    </span>
                </form>
            </div>
        }
        <hr />

        <div page-model="@Model.PagingInformation" page-action="Index" page-class-enabled="true" page-class="btn" page-class-normal="btn-outline-dark" page-class-selected="btn-primary" page-url-category="@Model.CurrentCategory" class="btn-group pull-right m-1"></div>

    </div>
</div>

HarrysGroceryStore/Views/Product/ProductDetail.cshtml
@model Product

<table>
    <tr>
        <th class="text-right"> Product Name: </th>
        <td class="p-2"> @Model.ProductName </td>
    </tr>
    <tr>
        <th class="text-right"> Category: </th>
        <td class="p-2"> @Model.Category </td>
    </tr>
    <tr>
        <th class="text-right"> Unit Price: </th>
        <td class="p-2"> @Model.Price.ToString("C") </td>
    </tr>
</table>
<hr />

<a asp-controller="Product" asp-action="UpdateProduct" asp-route-id="@Model.ProductId" class="btn btn-dark"> Edit Product </a>
<a asp-controller="Product" asp-action="DeleteProduct" class="btn btn-dark" asp-route-id="@Model.ProductId"> Delete Product </a>
<a asp-controller="Product" asp-action="Index" asp-route-id="@Model.ProductId" class="btn btn-dark"> Back </a>

HarrysGroceryStore/Views/Product/SearchProduct.cshtml
@model IQueryable<Product>


<hr />
@foreach (Product p in Model)
{
<table>
    <tr>
        <th class="text-right"> Product Name: </th>
        <td class="p-2"> @p.ProductName </td>
    </tr>
    <tr>
        <th class="text-right"> Category: </th>
        <td class="p-2"> @p.Category </td>
    </tr>
    <tr>
        <th class="text-right"> Unit Price: </th>
        <td class="p-2"> @p.Price.ToString("C") </td>
    </tr>
    <tr>
        <th class="text-right"> Supplier: </th>
        <td class="p-2"> @p.Supplier.CompanyName </td>
    </tr>
</table>
    <hr />
}

HarrysGroceryStore/Views/Product/UpdateProduct.cshtml
@model Product

<form method="post">
    <input type="hidden" asp-for="ProductId" />
    <table>
        <tr>
            <th><label class="font-weight-bold" asp-for="ProductName"> Product Name: </label></th>
            <td> <input asp-for="ProductName" /> </td>
        </tr>
        <tr>
            <th><label class="font-weight-bold" asp-for="Category"> Category: </label></th>
            <td> <input asp-for="Category" /> </td>
        </tr>
        <tr>
            <th> <label class="font-weight-bold" asp-for="Price"> Price: </label> </th>
            <td> <input asp-for="Price" /> </td>
        </tr>
        <tr>
            <th></th>
            <td> <input type="submit" class="btn btn-dark" value="Update Product" /> <input type="submit" class="btn btn-dark" asp-controller="Product" asp-action="ProductDetail" asp-route-id="@Model.ProductId" value="Cancel" /> </td>
        </tr>
    </table>
</form>