HarrysGroceryStore/Models/Supplier/EfSupplierRepository.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    public class EfSupplierRepository : ISupplierRepository
    {
        private AppDbContext _context;

        public EfSupplierRepository(AppDbContext context)
        {
            _context = context;
        }

        public Supplier AddSupplier(Supplier supplier)
        {
            _context.Suppliers.Add(supplier);
            _context.SaveChanges();
            return supplier;
        }

        public IQueryable<Supplier> GetAllSuppliers()
        {
            return _context.Suppliers;
        }

        public Supplier GetSupplierById(int supplierId)
        {
            Supplier supplier = _context.Suppliers.Include(s => s.Products).Where(s => s.SupplierId == supplierId).FirstOrDefault();
            return supplier;
        }

        public IQueryable<Supplier> GetSuppliersByKeyword(string keyword)
        {
            IQueryable<Supplier> suppliers = _context.Suppliers.Where(p => p.CompanyName.Contains(keyword));
            return suppliers;
        }

        public Supplier UpdateSupplier(Supplier supplier)
        {
            Supplier supplierToUpdate = _context.Suppliers.Find(supplier.SupplierId);
            if (supplierToUpdate != null)
            {
                supplierToUpdate.CompanyName = supplier.CompanyName;
                supplierToUpdate.ContactName = supplier.ContactName;
                supplierToUpdate.ContactEmail = supplier.ContactEmail;
                supplierToUpdate.ContactPhone = supplier.ContactPhone;
                _context.SaveChanges();
            }
            return supplierToUpdate;
        }

        public bool DeleteSupplier(int id)
        {
            Supplier supplierToDelete = GetSupplierById(id);
            if (supplierToDelete == null)
            {
                return false;
            }
            _context.Suppliers.Remove(supplierToDelete);
            _context.SaveChanges();
            return true;
        }
    }
}

HarrysGroceryStore/Models/Supplier/ISupplierRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    public interface ISupplierRepository
    {
        public Supplier AddSupplier(Supplier supplier);

        public IQueryable<Supplier> GetAllSuppliers();

        public Supplier GetSupplierById(int supplierId);

        public IQueryable<Supplier> GetSuppliersByKeyword(string keyword);

        public Supplier UpdateSupplier(Supplier supplier);

        public bool DeleteSupplier(int id);
    }
}

HarrysGroceryStore/Models/Supplier/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Models
{
    [Table("Suppliers")]

    public class Supplier
    {
        [Key]
        public int SupplierId { get; set; }

        public string CompanyName { get; set; }

        public string ContactName { get; set; }

        public string ContactEmail { get; set; }

        public string ContactPhone { get; set; }

        public List<Product> Products { get; set; }
    }
}

HarrysGroceryStore/Controllers/Supplier/SupplierController.cs
using HarrysGroceryStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrysGroceryStore.Controllers
{
    public class SupplierController : Controller
    {
        private int _pageSize = 10;
        private ISupplierRepository _repository;

        public SupplierController(ISupplierRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public IActionResult AddSupplier()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSupplier(Supplier supplier)
        {
            _repository.AddSupplier(supplier);
            return RedirectToAction("Index");
        }

        public IActionResult Index(int page = 1)
        {
            IQueryable<Supplier> allSuppliers = _repository.GetAllSuppliers();
            IQueryable<Supplier> someSuppliers = allSuppliers.OrderBy(p => p.SupplierId).Skip((page - 1) * _pageSize).Take(_pageSize);

            ListViewModel lvm = new ListViewModel();

            PagingInfo pi = new PagingInfo();
            pi.TotalItems = allSuppliers.Count();
            pi.ItemsPerPage = _pageSize;
            pi.CurrentPage = page;

            lvm.PagingInformation = pi;

            lvm.Suppliers = someSuppliers;

            return View(lvm);
        }

        public IActionResult SupplierDetail(int id)
        {
            Supplier supplier = _repository.GetSupplierById(id);
            if (supplier != null)
            {
                return View(supplier);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Search(string keyword)
        {
            IQueryable<Supplier> suppliers = _repository.GetSuppliersByKeyword(keyword);
            return View(suppliers);
        }

        [HttpGet]
        public IActionResult UpdateSupplier(int id)
        {
            Supplier supplier = _repository.GetSupplierById(id);
            if (supplier != null)
            {
                return View(supplier);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UpdateSupplier(Supplier supplier)
        {
            Supplier updatedSupplier = _repository.UpdateSupplier(supplier);
            return RedirectToAction("SupplierDetail", new { id = supplier.SupplierId });
        }

        [HttpGet]
        public IActionResult DeleteSupplier(int id)
        {
            Supplier supplier = _repository.GetSupplierById(id);
            if (supplier != null)
            {
                return View(supplier);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteSupplier(Supplier supplier, int id)
        {
            _repository.DeleteSupplier(id);
            return RedirectToAction("Index");
        }
    }
}

HarrysGroceryStore/Views/Supplier/AddSupplier.cshtml
@model Supplier

<form asp-controller="Supplier" asp-action="AddSupplier" method="post">
    <table>
        <tr>
            <th><label class="font-weight-bold" asp-for="CompanyName"> Company Name: </label></th>
            <td> <input asp-for="CompanyName" /> </td>
        </tr>
        <tr>
            <th> <label class="font-weight-bold" asp-for="ContactName"> Contact Name: </label> </th>
            <td> <input asp-for="ContactName" /> </td>
        </tr>
        <tr>
            <th><label class="font-weight-bold" asp-for="ContactEmail"> Contact Email: </label></th>
            <td> <input asp-for="ContactEmail"  /> </td>
        </tr>
        <tr>
            <th><label class="font-weight-bold" asp-for="ContactPhone"> Contact Phone: </label></th>
            <td> <input asp-for="ContactPhone" /> </td>
        </tr>
        <tr>
            <th></th>
            <td> <input type="submit" class="btn btn-dark" value="Add New Supplier" /> <input type="submit" class="btn btn-warning" asp-action="Index" value="Back" /> </td>
        </tr>
    </table>
</form>

HarrysGroceryStore/Views/Supplier/DeleteSupplier.cshtml
@model Supplier

<label class="font-weight-bold"> Supplier Id: </label> @Model.SupplierId
<br />
<label class="font-weight-bold"> Company Name: </label> @Model.CompanyName
<br />
<label class="font-weight-bold"> Contact Name: </label> @Model.ContactName
<br />
<label class="font-weight-bold"> Contact Email: </label> @Model.ContactEmail
<br />
<label class="font-weight-bold"> Contact Number: </label> @Model.ContactPhone
<br />
<hr />
<h4> Are You Sure? </h4>
<form method="post">
    <input type="submit" asp-action="DeleteSupplier" class="btn btn-danger" value="Delete" />
    <input type="submit" asp-action="SupplierDetail" class="btn btn-warning" asp-route-id="@Model.SupplierId" formmethod="get" value="Cancel" />
</form>

HarrysGroceryStore/Views/Supplier/Index.cshtml
@model ListViewModel

<div class="bg-dark p-2 text-white text-center">
    <h3><span class="navbar-brand ml-2 badge"> List of @Model.Suppliers.Count() Suppliers </span></h3>
</div>
<hr />

@foreach (var supplier in Model.Suppliers)
{
    <div class="card card-outline-primary m-1 p-1">
        <div class="fg-faded p-1">
            <h4>
                <a asp-action="SupplierDetail" asp-route-id=" @supplier.SupplierId"> @supplier.CompanyName </a>
            </h4>
        </div>
    </div>
}

<a asp-controller="Supplier" asp-action="AddSupplier" class="btn btn-dark"> Add a new Supplier </a>
<a asp-controller="Home" asp-action="AdminMain" class="ml-2 btn btn-warning">Back</a>
<hr />

<div page-model="@Model.PagingInformation" page-action="Index" page-class-enabled="true" page-class="btn" page-class-normal="btn-outline-dark" page-class-selected="btn-primary" class="btn-group pull-right m-1"></div>

HarrysGroceryStore/Views/Supplier/SearchSupplier.cshtml
@model IQueryable<Supplier>


<hr />
@foreach (Supplier s in Model)
{
    <label class="font-weight-bold"> Supplier Id: </label> @s.SupplierId
    <br />
    <label class="font-weight-bold"> Company Name: </label> @s.CompanyName
    <br />
    <label class="font-weight-bold"> Contact Name: </label> @s.ContactName
    <br />
    <label class="font-weight-bold"> Contact Email: </label> @s.ContactEmail
    <br />
    <label class="font-weight-bold"> Contact Number: </label> @s.ContactPhone
    <br />
    <hr />
}

HarrysGroceryStore/Views/Supplier/SupplierDetail.cshtml
@model Supplier

<table>
    <tr>
        <th class="text-right"> Company Name: </th>
        <td class="p-2"> @Model.CompanyName </td>
    </tr>
    <tr>
        <th class="text-right"> Contact Name: </th>
        <td class="p-2"> @Model.ContactName </td>
    </tr>
    <tr>
        <th class="text-right"> Contact Email: </th>
        <td class="p-2"> @Model.ContactEmail </td>
    </tr>
    <tr>
        <th class="text-right"> Contact Number : </th>
        <td class="p-2"> @Model.ContactPhone </td>
    </tr>
</table>
<hr />


<a asp-controller="Supplier" asp-action="UpdateSupplier" asp-route-id="@Model.SupplierId" class="btn btn-primary"> Edit Supplier </a>
<a asp-controller="Supplier" asp-action="DeleteSupplier" class="btn btn-danger" asp-route-id="@Model.SupplierId"> Delete Supplier </a>
<a asp-controller="Product" asp-action="ProductDetail" asp-route-id="@Model.SupplierId" class="btn btn-warning"> Back </a>

HarrysGroceryStore/Views/Supplier/UpdateSupplier.cshtml
@model Supplier

<form method="post">
    <input type="hidden" asp-for="SupplierId" />
    <table>
        <tr>
            <th><label class="font-weight-bold" asp-for="CompanyName"> Company Name: </label></th>
            <td> <input asp-for="CompanyName" /> </td>
        </tr>
        <tr>
            <th> <label class="font-weight-bold" asp-for="ContactName"> Contact Name: </label> </th>
            <td> <input asp-for="ContactName" /> </td>
        </tr>
        <tr>
            <th><label class="font-weight-bold" asp-for="ContactEmail"> Contact Email: </label></th>
            <td> <input asp-for="ContactEmail" /> </td>
        </tr>
        <tr>
            <th><label class="font-weight-bold" asp-for="ContactPhone"> Contact Phone: </label></th>
            <td> <input asp-for="ContactPhone" /> </td>
        </tr>
        <tr>
            <th></th>
            <td> <input type="submit" class="btn btn-primary" value="Update Supplier" /> <input type="submit" class="btn btn-warning" asp-controller="Supplier" asp-action="SupplierDetail" asp-route-id="@Model.SupplierId" value="Cancel" /> </td>
        </tr>
    </table>
</form>